### ISSUE TITLE
Problem with pod

### ISSUE THREAD

**Issue by fmirault** [leandromperez/specleaks#2]
I tried to import SpecLeaks with cocoapods (specifying pod 'SpecLeaks' in my podfile), but it seems that many files are missing.

In fact, I only got LeakTest.swift, but all the other files are not downloaded.

Maybe there is a problem with your pod configuration ?

**Comment by MrAtiebatie** [comment]
I have the same problem. Any solution?

**Comment by leandromperez** [comment]
I just returned from my vacations. I'll take a look at it asap!

**Comment by fmirault** [comment]
Do you have some updates ?

**Comment by leandromperez** [comment]
@fmirault Sorry for the late late response, I have been too busy. I just uploaded a new version 0.1.1 and tested it with a blank app. You should be able to use SpecLeaks now.

Remember to set it in your test target, something like this:

target 'TestingAppTests' do **TestingApp** is the default target while **TestingAppTests** is the testing target
    pod 'SpecLeaks'
end

Can you please let me know if that works for you?

@mbarnach I had to remove macOS support because it was causing issues with lib lint and couldn't push to trunk. I created a feature branch here: https://github.com/leandromperez/specleaks/tree/feature/0.1.1.macos.support in case you're interested in taking a look and run pod lib lint. I couldn't found the issue.

**Comment by leandromperez** [comment]
@MrAtiebatie Can you try now?

**Comment by MrAtiebatie** [comment]
I still didn't received the right files through Cocoapods. However take a look at my fork:
[MrAtiebatie/specleaks](https://github.com/MrAtiebatie/specleaks)
I managed to get it to work by removing the swift version from the podspec file.

**Comment by leandromperez** [comment]
Hi @MrAtiebatie,
I've just added support for Swift 5 and Travis.CI is running the tests. I'm closing this issue, if you are still experiencing this, could you please re-open it?
Thanks!
